trace:
  endpoint: http://127.0.0.1:9080/v1/trace
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9091
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:password@tcp(127.0.0.1:3307)/goweb?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  apollo:
    addr: "http://127.0.0.1:8080"
    app_id: "ktaros-mono-repo"
    cluster: "default"
    namespace: ["load.json","service.json"]
    secret: "7308b9cee8764784aa226bdf0c1ca48d"
  kafka:
    addr: ["127.0.0.1:9092"]
    send_topic: ["create_msg"]
    recive_topic: []
    group: []
    mode: 2 
